server:
  port: 8081

spring:
  application:
    name: pulsar-starter

cycads:
  pulsar:
    service-url: pulsar://localhost:6650
#    consumer:
#      schema-type: string
#      subscription-name: TEST-SUB
#    listener:
#      batch: false
  # 定义Topic
  listener-topics: TOPIC_TEST